[package]
name = "mal"
version = "0.1.0"
authors = ["tamamu <tamamu.1r1s@gmail.com>"]


[dependencies]
rustbox = "*"
gl = "*"
libc = "*"
glutin = "*"

[dependencies.nanovg]
version = "*"
features = ["gl3"]

[target.'cfg(unix)'.dependencies]
x11 = {version = "2.12.0", features = ["xlib"]}
